
'use client';

import { useState, useEffect } from 'react';
import API from '../../lib/api';

export default function FilesGuidelines() {
  const [activeTab, setActiveTab] = useState('projects');
  const [showCreateProjectModal, setShowCreateProjectModal] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [selectedProject, setSelectedProject] = useState<any>(null);
  const [selectedFile, setSelectedFile] = useState<any>(null);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [isUploading, setIsUploading] = useState(false);
  const [parseProgress, setParseProgress] = useState(0);
  const [isParsing, setIsParsing] = useState(false);
  const [showParseResults, setShowParseResults] = useState(false);
  const [parseResults, setParseResults] = useState<any>(null);
  const [cancelParsing, setCancelParsing] = useState(false);
  const [currentParsingFileId, setCurrentParsingFileId] = useState<number | null>(null);
  const [aiDraftSettings, setAiDraftSettings] = useState({
    autoGenerate: true,
    generateOnAssign: true
  });

  // 新项目创建表单状态
  const [newProjectForm, setNewProjectForm] = useState({
    name: '',
    description: '',
    type: '',
    autoGenerateDraft: true // 默认开启AI草稿自动生成
  });

  const [projects, setProjects] = useState<any[]>([]);
  const [isLoadingProjects, setIsLoadingProjects] = useState(false);
  const [isLoadingFiles, setIsLoadingFiles] = useState(false);

  // Load projects from API
  useEffect(() => {
    loadProjects();
  }, []);

  const loadProjects = async () => {
    setIsLoadingProjects(true);
    try {
      const result = await API.projects.getAll();
      // Transform API response to match component structure
      const projectList = Array.isArray(result) ? result : result.projects || [];

      // Load statistics for each project
      const transformedProjects = await Promise.all(
        projectList.map(async (project: any) => {
          let fileCount = 0;
          let totalPages = 0;
          let totalTables = 0;

          try {
            // Load files for this project to calculate statistics
            const filesResult = await API.files.getByProject(project.project_id);
            const files = filesResult.files || [];
            fileCount = files.length;

            // For each file, get parse status to get page and table counts
            for (const file of files) {
              try {
                const parseStatus = await API.parse.getStatus(file.file_id);
                totalPages += parseStatus.page_count || 0;
                totalTables += parseStatus.tables_found || 0;
              } catch (error) {
                // If parse status fails, skip this file
                console.warn(`Could not get parse status for file ${file.file_id}`);
              }
            }
          } catch (error) {
            console.warn(`Could not load files for project ${project.project_id}`);
          }

          return {
            id: project.project_id,
            name: project.name,
            description: project.description || '',
            fileCount: fileCount,
            totalPages: totalPages,
            totalTables: totalTables,
            status: project.status,
            createdAt: new Date(project.created_at).toLocaleDateString(),
            autoGenerateDraft: true,
            files: []
          };
        })
      );

      setProjects(transformedProjects);
    } catch (error) {
      console.error('Failed to load projects:', error);
      alert('加载项目失败，请检查后端连接');
    } finally {
      setIsLoadingProjects(false);
    }
  };

  // Load files for a specific project
  const loadProjectFiles = async (projectId: number) => {
    console.log('📂 Loading files for project:', projectId);
    try {
      const filesResult = await API.files.getByProject(projectId);
      console.log('✅ Files loaded:', filesResult);

      // Transform files to match component structure
      const transformedFiles = await Promise.all(
        (filesResult.files || []).map(async (file: any) => {
          // Get parse status for each file to get page count and table count
          let pageCount = 0;
          let tableCount = 0;
          let fileStatus = 'pending';

          try {
            const parseStatus = await API.parse.getStatus(file.file_id);
            pageCount = parseStatus.page_count || 0;
            tableCount = parseStatus.tables_found || 0;
            fileStatus = parseStatus.status || 'pending';
            console.log(`📊 File ${file.file_id} parse status:`, parseStatus);
          } catch (error) {
            console.warn(`⚠️ Could not fetch parse status for file ${file.file_id}:`, error);
          }

          return {
            id: file.file_id,
            name: file.file_name,
            pages: pageCount,
            tables: tableCount,
            status: fileStatus,
            uploadedAt: new Date(file.created_at).toLocaleDateString(),
            size: `${(file.file_size / 1024 / 1024).toFixed(1)} MB`,
            tasks: tableCount, // Tasks are created per table
            completedTasks: 0, // TODO: Get from backend
            parsedTables: [] // TODO: Get from backend
          };
        })
      );

      return transformedFiles;
    } catch (error) {
      console.error('❌ Failed to load files:', error);
      throw error;
    }
  };

  // Handle viewing a project's files
  const handleViewProject = async (project: any) => {
    console.log('👁️ Viewing project:', project.name);
    setSelectedProject(project);
    setIsLoadingFiles(true);

    try {
      const files = await loadProjectFiles(project.id);
      setSelectedProject({
        ...project,
        files: files
      });
      console.log('✅ Project files loaded successfully');
    } catch (error) {
      console.error('❌ Failed to load project files:', error);
      alert('加载项目文件失败，请检查后端连接');
    } finally {
      setIsLoadingFiles(false);
    }
  };

  // Handle viewing tables for a specific file
  const handleViewTables = async (file: any) => {
    console.log('📊 Viewing tables for file:', file.name);
    setSelectedFile(file);
    
    try {
      // Get tables data from backend
      const tablesData = await API.parse.getTables(file.id);
      console.log('✅ Tables data loaded:', tablesData);
      
      // Transform tables data to match component structure
      const transformedTables = tablesData.tables.map((table: any) => ({
        id: table.table_id,
        page: table.page_number,
        bbox: table.bbox ? [table.bbox.x, table.bbox.y, table.bbox.width, table.bbox.height] : [0, 0, 0, 0],
        rows: table.rows?.length || 0,
        cols: table.headers?.[0]?.length || 0,
        complexity: 'medium', // Default complexity
        status: 'pending',
        hasFootnotes: false, // Default value
        // Add actual table data for display
        headers: table.headers || [],
        tableRows: table.rows || [],
        confidence: table.confidence || 0
      }));
      
      setSelectedFile({
        ...file,
        parsedTables: transformedTables
      });
    } catch (error) {
      console.error('❌ Failed to load tables:', error);
      alert('加载表格数据失败，请检查后端连接');
    }
  };

  // Handle ESC key to close modal
  useEffect(() => {
    const handleEscKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && selectedFile) {
        setSelectedFile(null);
      }
    };

    if (selectedFile) {
      document.addEventListener('keydown', handleEscKey);
      // Prevent body scroll when modal is open
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscKey);
      document.body.style.overflow = 'unset';
    };
  }, [selectedFile]);

  const mockProjects = [
    {
      id: 1,
      name: 'Financial Analysis Q4 2024',
      description: '第四季度财务分析项目',
      fileCount: 3,
      totalPages: 135,
      totalTables: 42,
      status: 'active',
      createdAt: '2024-01-15',
      autoGenerateDraft: true, // 项目级AI草稿自动生成设置
      files: [
        {
          id: 1,
          name: 'Financial Report Q4 2024.pdf',
          pages: 45,
          tables: 15,
          status: 'completed',
          uploadedAt: '2024-01-15',
          size: '2.3 MB',
          tasks: 15,
          completedTasks: 15,
          parsedTables: [
            { id: 1, page: 5, bbox: [100, 200, 400, 350], rows: 8, cols: 4, complexity: 'medium', status: 'completed' },
            { id: 2, page: 12, bbox: [80, 150, 500, 400], rows: 12, cols: 6, complexity: 'high', status: 'completed' },
            { id: 3, page: 23, bbox: [120, 180, 450, 320], rows: 6, cols: 3, complexity: 'low', status: 'completed' }
          ]
        },
        {
          id: 2,
          name: 'Budget Analysis.pdf',
          pages: 32,
          tables: 8,
          status: 'in_progress',
          uploadedAt: '2024-01-18',
          size: '1.8 MB',
          tasks: 8,
          completedTasks: 5,
          parsedTables: [
            { id: 4, page: 3, bbox: [90, 160, 480, 300], rows: 10, cols: 5, complexity: 'medium', status: 'in_progress' },
            { id: 5, page: 8, bbox: [110, 140, 420, 280], rows: 7, cols: 4, complexity: 'low', status: 'pending' }
          ]
        },
        {
          id: 3,
          name: 'Revenue Forecast.pdf',
          pages: 58,
          tables: 19,
          status: 'pending',
          uploadedAt: '2024-01-20',
          size: '4.1 MB',
          tasks: 19,
          completedTasks: 0,
          parsedTables: [
            { id: 6, page: 7, bbox: [95, 170, 460, 340], rows: 15, cols: 7, complexity: 'high', status: 'pending' },
            { id: 7, page: 15, bbox: [105, 190, 440, 310], rows: 9, cols: 4, complexity: 'medium', status: 'pending' }
          ]
        }
      ]
    },
    {
      id: 2,
      name: 'Product Documentation Review',
      description: '产品文档审核项目',
      fileCount: 2,
      totalPages: 89,
      totalTables: 22,
      status: 'active',
      createdAt: '2024-01-10',
      autoGenerateDraft: false, // 项目级AI草稿自动生成设置
      files: [
        {
          id: 4,
          name: 'Product Specification.pdf',
          pages: 45,
          tables: 12,
          status: 'in_progress',
          uploadedAt: '2024-01-12',
          size: '3.2 MB',
          tasks: 12,
          completedTasks: 8,
          parsedTables: []
        },
        {
          id: 5,
          name: 'User Manual.pdf',
          pages: 44,
          tables: 10,
          status: 'completed',
          uploadedAt: '2024-01-14',
          size: '2.8 MB',
          tasks: 10,
          completedTasks: 10,
          parsedTables: []
        }
      ]
    }
  ];

  const guidelines = [
    {
      id: 1,
      title: '表格标注规范',
      description: '如何正确标注PDF中的表格结构和内容',
      type: 'document',
      updatedAt: '2024-01-10',
      url: '#'
    },
    {
      id: 2,
      title: '文本提取指南',
      description: '文本内容提取的标准流程和质量要求',
      type: 'video',
      updatedAt: '2024-01-08',
      url: '#'
    },
    {
      id: 3,
      title: '质量检查清单',
      description: '标注完成后的自检项目和标准',
      type: 'checklist',
      updatedAt: '2024-01-05',
      url: '#'
    }
  ];

  const handleFileUpload = async (file: globalThis.File) => {
    console.log('🎯 handleFileUpload 被调用', {
      fileName: file.name,
      fileSize: file.size,
      fileType: file.type,
      selectedProject: selectedProject
    });

    if (!selectedProject) {
      console.error('❌ 未选择项目');
      alert('❌ 请先选择项目');
      return;
    }

    setIsUploading(true);
    setUploadProgress(0);

    try {
      // 1. 上传文件到后端
      console.log(`📤 开始上传文件到项目 ${selectedProject.id}...`);
      console.log('API.files.upload 参数:', { projectId: selectedProject.id, file });

      const uploadResult = await API.files.upload(selectedProject.id, file);
      console.log('✅ 上传成功:', uploadResult);

      setUploadProgress(100);
      setIsUploading(false);

      // 刷新文件列表以显示新上传的文件
      console.log('🔄 刷新文件列表...');
      const files = await loadProjectFiles(selectedProject.id);
      setSelectedProject({
        ...selectedProject,
        files: files
      });

      // 2. 自动触发解析
      console.log('🧠 准备触发解析...');
      await startParsing(uploadResult.file_id, file.name);

    } catch (error) {
      console.error('❌ 上传失败 - 详细错误:', error);
      console.error('错误堆栈:', error instanceof Error ? error.stack : 'No stack');
      alert(`上传失败: ${error instanceof Error ? error.message : JSON.stringify(error)}`);
      setIsUploading(false);
      setUploadProgress(0);
    }
  };

  const startParsing = async (fileId: number, fileName: string) => {
    setIsParsing(true);
    setParseProgress(0);
    setCancelParsing(false);
    setCurrentParsingFileId(fileId);

    try {
      // 1. 触发解析
      console.log(`🧠 触发文件 ${fileId} 的解析...`);
      const parseResult = await API.parse.trigger(fileId);
      console.log('✅ 解析已启动:', parseResult);

      setParseProgress(50);

      // 2. 轮询解析状态（模拟）
      // 实际项目中可以用 polling 或 websocket 监听状态
      const checkStatus = async () => {
        // Check if user cancelled
        if (cancelParsing) {
          console.log('❌ 用户取消了解析');
          setIsParsing(false);
          setParseProgress(0);
          setCurrentParsingFileId(null);
          return;
        }

        const status = await API.parse.getStatus(fileId);
        console.log('📊 解析状态更新:', {
          file_id: fileId,
          status: status.status,
          tables_found: status.tables_found,
          page_count: status.page_count,
          timestamp: new Date().toISOString()
        });

        if (status.status === 'completed') {
          console.log('🎉 解析完成！', {
            file_id: fileId,
            fileName: fileName,
            pages: status.page_count,
            tables: status.tables_found
          });

          setParseProgress(100);
          setIsParsing(false);

          // 获取表格数据
          const tablesData = await API.parse.getTables(fileId);
          console.log('✅ 获取表格数据成功:', tablesData);

          // 显示解析结果
          const results = {
            file_id: fileId, // 添加 file_id 用于后续任务创建
            fileName: fileName,
            totalPages: status.page_count,
            tablesFound: tablesData.total,
            tables: tablesData.tables.map((table: any) => ({
              id: table.table_id,
              page: table.page_number,
              bbox: table.bbox ? [table.bbox.x, table.bbox.y, table.bbox.width, table.bbox.height] : [0, 0, 0, 0],
              rows: table.rows?.length || 0,
              cols: table.headers?.[0]?.length || 0,
              complexity: 'medium', // 后端暂无此字段
              hasFootnotes: false
            }))
          };
          setParseResults(results);
          setShowParseResults(true);

          // 刷新文件列表以显示更新后的表格数
          console.log('🔄 刷新文件列表，显示最新的页数和表格数...');
          if (selectedProject) {
            const files = await loadProjectFiles(selectedProject.id);
            setSelectedProject({
              ...selectedProject,
              files: files
            });
            console.log('✅ 文件列表已刷新');
          }

        } else if (status.status === 'failed') {
          console.error('❌ 解析失败:', status);
          setIsParsing(false);
          alert(`❌ 解析失败: ${status.processing_error || '未知错误'}`);
        } else {
          // 继续轮询
          console.log(`⏳ 解析进行中 (${status.status})，2秒后继续检查...`);
          setTimeout(checkStatus, 2000);
          setParseProgress(prev => Math.min(prev + 10, 90));
        }
      };

      // 开始轮询
      setTimeout(checkStatus, 1000);

    } catch (error) {
      console.error('❌ 解析失败:', error);
      alert(`解析失败: ${error instanceof Error ? error.message : '未知错误'}`);
      setIsParsing(false);
      setParseProgress(0);
    }
  };

  const handleConfirmParsing = async () => {
    if (!parseResults || !selectedProject) {
      console.error('❌ Missing parseResults or selectedProject');
      return;
    }

    try {
      console.log('📝 Creating tasks for file:', parseResults.file_id);

      // 调用后端 API 创建任务
      const tasksResult = await API.tasks.bulkCreate(
        parseResults.file_id,
        undefined // 不指定分配对象，任务将处于待分配状态
      );

      console.log('✅ Tasks created:', tasksResult);

      // 刷新文件列表以显示更新后的任务数
      console.log('🔄 Refreshing file list...');
      const files = await loadProjectFiles(selectedProject.id);

      // Recalculate project statistics
      let totalPages = 0;
      let totalTables = 0;
      for (const f of files) {
        try {
          const parseStatus = await API.parse.getStatus(f.id);
          totalPages += parseStatus.page_count || 0;
          totalTables += parseStatus.tables_found || 0;
        } catch (error) {
          console.warn(`Could not get parse status for file ${f.id}`);
        }
      }

      setSelectedProject({
        ...selectedProject,
        files: files,
        fileCount: files.length,
        totalPages: totalPages,
        totalTables: totalTables
      });

      // Also refresh the projects list to update the card
      await loadProjects();

      // 关闭弹窗
      setShowParseResults(false);
      setShowUploadModal(false);
      setParseResults(null);

      // 显示成功消息
      alert(`✅ 成功创建 ${tasksResult.total} 个任务！已发送到系统分配管理。`);

    } catch (error) {
      console.error('❌ Task creation failed:', error);
      alert(`❌ 创建任务失败: ${error instanceof Error ? error.message : '未知错误'}`);
    }
  };

  const handleDeleteProject = async (project: any) => {
    if (!confirm(`确定要删除项目 "${project.name}" 吗？\n\n此操作将删除该项目下的所有文件、表格和任务，且无法恢复。`)) {
      return;
    }

    try {
      console.log('🗑️ 删除项目:', project.id);

      await API.projects.delete(project.id);

      console.log('✅ 项目删除成功');

      // 刷新项目列表
      await loadProjects();

      // 如果当前正在查看被删除的项目，返回项目列表
      if (selectedProject?.id === project.id) {
        setSelectedProject(null);
      }

      alert('✅ 项目已删除');
    } catch (error) {
      console.error('❌ 删除项目失败:', error);
      alert(`❌ 删除失败: ${error instanceof Error ? error.message : '未知错误'}`);
    }
  };

  const handleDeleteFile = async (file: any) => {
    if (!confirm(`确定要删除文件 "${file.name}" 吗？\n\n此操作将同时删除该文件的所有解析表格和相关任务，且无法恢复。`)) {
      return;
    }

    try {
      console.log('🗑️ 删除文件:', file.id);

      await API.files.delete(file.id);

      console.log('✅ 文件删除成功');

      // 刷新文件列表
      if (selectedProject) {
        const files = await loadProjectFiles(selectedProject.id);

        // Recalculate project statistics
        let totalPages = 0;
        let totalTables = 0;
        for (const f of files) {
          try {
            const parseStatus = await API.parse.getStatus(f.id);
            totalPages += parseStatus.page_count || 0;
            totalTables += parseStatus.tables_found || 0;
          } catch (error) {
            console.warn(`Could not get parse status for file ${f.id}`);
          }
        }

        setSelectedProject({
          ...selectedProject,
          files: files,
          fileCount: files.length,
          totalPages: totalPages,
          totalTables: totalTables
        });

        // Also refresh the projects list to update the card
        await loadProjects();
      }

      alert('✅ 文件已删除');
    } catch (error) {
      console.error('❌ 删除文件失败:', error);
      alert(`❌ 删除失败: ${error instanceof Error ? error.message : '未知错误'}`);
    }
  };

  const getStatusColor = (status: string) => {
    const colorMap: { [key: string]: string } = {
      'pending': 'bg-yellow-100 text-yellow-800',
      'in_progress': 'bg-blue-100 text-blue-800',
      'completed': 'bg-green-100 text-green-800',
      'active': 'bg-green-100 text-green-800'
    };
    return colorMap[status] || 'bg-gray-100 text-gray-800';
  };

  const getStatusLabel = (status: string) => {
    const labelMap: { [key: string]: string } = {
      'pending': '待处理',
      'in_progress': '进行中',
      'completed': '已完成',
      'active': '进行中'
    };
    return labelMap[status] || status;
  };

  const getTypeIcon = (type: string) => {
    const iconMap: { [key: string]: string } = {
      'document': 'ri-file-text-line',
      'video': 'ri-video-line',
      'checklist': 'ri-checkbox-line'
    };
    return iconMap[type] || 'ri-file-line';
  };

  const getProgressPercentage = (completed: number, total: number) => {
    return total > 0 ? Math.round((completed / total) * 100) : 0;
  };

  const getComplexityColor = (complexity: string) => {
    switch (complexity) {
      case 'high': return 'bg-red-100 text-red-800';
      case 'medium': return 'bg-yellow-100 text-yellow-800';
      case 'low': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getComplexityLabel = (complexity: string) => {
    switch (complexity) {
      case 'high': return '复杂';
      case 'medium': return '中等';
      case 'low': return '简单';
      default: return complexity;
    }
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold text-gray-900">文件与指南管理</h2>
          <p className="text-sm text-gray-600 mt-1">管理项目文件和标注指南，支持智能解析与任务分配</p>
        </div>
        {!selectedProject && (
          <button
            onClick={() => setShowCreateProjectModal(true)}
            className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
          >
            <i className="ri-add-line w-4 h-4 flex items-center justify-center"></i>
            <span>创建项目</span>
          </button>
        )}
        {selectedProject && (
          <div className="flex items-center space-x-3">
            <button
              onClick={() => setSelectedProject(null)}
              className="text-gray-600 hover:text-gray-700 px-3 py-2 rounded-lg hover:bg-gray-100 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
            >
              <i className="ri-arrow-left-line w-4 h-4 flex items-center justify-center"></i>
              <span>返回项目列表</span>
            </button>
            <button
              onClick={() => setShowUploadModal(true)}
              className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center space-x-2 whitespace-nowrap cursor-pointer"
            >
              <i className="ri-upload-line w-4 h-4 flex items-center justify-center"></i>
              <span>上传PDF</span>
            </button>
          </div>
        )}
      </div>

      {/* Breadcrumb */}
      {selectedProject && (
        <div className="flex items-center space-x-2 text-sm text-gray-600">
          <span>Project Files</span>
          <i className="ri-arrow-right-s-line w-4 h-4 flex items-center justify-center"></i>
          <span className="font-medium text-gray-900">{selectedProject.name}</span>
        </div>
      )}

      {/* Tabs */}
      <div className="border-b border-gray-200">
        <nav className="flex space-x-8">
          {[
            { id: 'projects', label: '项目文件', icon: 'ri-folder-line' },
            { id: 'guidelines', label: '标注指南', icon: 'ri-book-line' }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id);
                if (tab.id === 'projects') {
                  setSelectedProject(null);
                }
              }}
              className={`flex items-center space-x-2 py-4 px-1 border-b-2 font-medium text-sm whitespace-nowrap cursor-pointer ${
                activeTab === tab.id
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              <i className={`${tab.icon} w-4 h-4 flex items-center justify-center`}></i>
              <span>{tab.label}</span>
            </button>
          ))}
        </nav>
      </div>

      {activeTab === 'projects' && !selectedProject && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {projects.map((project) => (
            <div key={project.id} className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center space-x-3 flex-1">
                  <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                    <i className="ri-folder-3-line w-5 h-5 flex items-center justify-center text-blue-600"></i>
                  </div>
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-gray-900">{project.name}</h3>
                    <p className="text-sm text-gray-600">{project.description}</p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <span className={`px-2 py-1 text-xs rounded-full ${getStatusColor(project.status)}`}>
                    {getStatusLabel(project.status)}
                  </span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDeleteProject(project);
                    }}
                    className="text-gray-400 hover:text-red-600 hover:bg-red-50 p-2 rounded-lg transition-colors"
                    title="删除项目"
                  >
                    <i className="ri-delete-bin-line w-4 h-4"></i>
                  </button>
                </div>
              </div>
              
              <div className="space-y-3 mb-4">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">文件数量</span>
                  <span className="font-medium text-gray-900">{project.fileCount} 个</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">总页数</span>
                  <span className="font-medium text-gray-900">{project.totalPages} 页</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">表格数量</span>
                  <span className="font-medium text-gray-900">{project.totalTables} 个</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">AI草稿自动生成</span>
                  <span className={`px-2 py-1 text-xs rounded-full ${project.autoGenerateDraft ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                    {project.autoGenerateDraft ? '已启用' : '已关闭'}
                  </span>
                </div>
              </div>

              <button
                onClick={() => handleViewProject(project)}
                className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 text-sm font-medium whitespace-nowrap cursor-pointer"
              >
                查看文件
              </button>
            </div>
          ))}
          
          <div className="bg-gray-50 rounded-lg border-2 border-dashed border-gray-300 p-6 flex flex-col items-center justify-center">
            <i className="ri-add-line w-8 h-8 flex items-center justify-center text-gray-400 mb-2"></i>
            <h3 className="text-sm font-medium text-gray-900 mb-1">创建新项目</h3>
            <p className="text-xs text-gray-500 text-center mb-4">创建项目后可以上传PDF文件</p>
            <button
              onClick={() => setShowCreateProjectModal(true)}
              className="text-blue-600 hover:text-blue-700 text-sm cursor-pointer"
            >
              创建项目
            </button>
          </div>
        </div>
      )}

      {activeTab === 'projects' && selectedProject && (
        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
          <div className="p-4 bg-gray-50 border-b border-gray-200">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">{selectedProject.name}</h3>
                <p className="text-sm text-gray-600">{selectedProject.description}</p>
              </div>
              <div className="flex items-center space-x-4 text-sm text-gray-600">
                <div className="flex items-center space-x-1">
                  <i className="ri-file-line w-4 h-4 flex items-center justify-center"></i>
                  <span>{selectedProject.files?.length || selectedProject.fileCount || 0} 个文件</span>
                </div>
                <div className="flex items-center space-x-1">
                  <i className="ri-pages-line w-4 h-4 flex items-center justify-center"></i>
                  <span>{selectedProject.totalPages || 0} 页</span>
                </div>
                <div className="flex items-center space-x-1">
                  <i className="ri-table-line w-4 h-4 flex items-center justify-center"></i>
                  <span>{selectedProject.totalTables || 0} 个表格</span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="text-left py-3 px-4 font-medium text-gray-900">文件名</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-900">页数/表格</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-900">任务进度</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-900">状态</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-900">上传时间</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-900">操作</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {selectedProject.files.map((file: any) => (
                  <tr key={file.id} className="hover:bg-gray-50">
                    <td className="py-4 px-4">
                      <div className="flex items-center space-x-3">
                        <i className="ri-file-pdf-line w-5 h-5 flex items-center justify-center text-red-500"></i>
                        <div>
                          <div className="font-medium text-gray-900">{file.name}</div>
                          <div className="text-sm text-gray-500">{file.size}</div>
                        </div>
                      </div>
                    </td>
                    <td className="py-4 px-4">
                      <div className="text-sm">
                        <div className="text-gray-900">{file.pages} 页</div>
                        <div className="text-gray-500">{file.tables} 个表格</div>
                      </div>
                    </td>
                    <td className="py-4 px-4">
                      <div className="space-y-1">
                        <div className="flex items-center justify-between text-sm">
                          <span>{file.completedTasks}/{file.tasks}</span>
                          <span className="text-gray-500">{getProgressPercentage(file.completedTasks, file.tasks)}%</span>
                        </div>
                        <div className="w-24 bg-gray-200 rounded-full h-2">
                          <div
                            className="bg-blue-500 h-2 rounded-full"
                            style={{ width: `${getProgressPercentage(file.completedTasks, file.tasks)}%` }}
                          ></div>
                        </div>
                      </div>
                    </td>
                    <td className="py-4 px-4">
                      <span className={`px-2 py-1 text-xs rounded-full ${getStatusColor(file.status)}`}>
                        {getStatusLabel(file.status)}
                      </span>
                    </td>
                    <td className="py-4 px-4">
                      <span className="text-sm text-gray-600">{file.uploadedAt}</span>
                    </td>
                    <td className="py-4 px-4">
                      <div className="flex items-center space-x-2">
                        <button
                          onClick={() => handleViewTables(file)}
                          className="text-blue-600 hover:text-blue-700 text-sm cursor-pointer"
                        >
                          查看表格
                        </button>
                        <button className="text-gray-600 hover:text-gray-700 text-sm cursor-pointer">
                          替换
                        </button>
                        <button
                          onClick={() => handleDeleteFile(file)}
                          className="text-red-600 hover:text-red-700 text-sm cursor-pointer"
                        >
                          删除
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          
          {isLoadingFiles && (
            <div className="p-8 text-center">
              <i className="ri-loader-4-line w-12 h-12 flex items-center justify-center text-blue-600 mx-auto mb-4 animate-spin"></i>
              <h3 className="text-lg font-medium text-gray-900 mb-2">加载文件中...</h3>
              <p className="text-gray-600">请稍候</p>
            </div>
          )}

          {!isLoadingFiles && selectedProject.files.length === 0 && (
            <div className="p-8 text-center">
              <i className="ri-file-upload-line w-12 h-12 flex items-center justify-center text-gray-300 mx-auto mb-4"></i>
              <h3 className="text-lg font-medium text-gray-900 mb-2">项目中暂无文件</h3>
              <p className="text-gray-600 mb-4">上传PDF文件开始标注任务</p>
              <button
                onClick={() => setShowUploadModal(true)}
                className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 whitespace-nowrap cursor-pointer"
              >
                上传PDF文件
              </button>
            </div>
          )}
        </div>
      )}

      {activeTab === 'guidelines' && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {guidelines.map((guide) => (
            <div key={guide.id} className="bg-white rounded-lg shadow-sm p-6">
              <div className="flex items-start space-x-3">
                <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                  <i className={`${getTypeIcon(guide.type)} w-5 h-5 flex items-center justify-center text-blue-600`}></i>
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">{guide.title}</h3>
                  <p className="text-sm text-gray-600 mb-4">{guide.description}</p>
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-gray-500">更新于 {guide.updatedAt}</span>
                    <button className="text-blue-600 hover:text-blue-700 text-sm cursor-pointer">
                      查看详情
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
          
          <div className="bg-gray-50 rounded-lg border-2 border-dashed border-gray-300 p-6 flex flex-col items-center justify-center">
            <i className="ri-add-line w-8 h-8 flex items-center justify-center text-gray-400 mb-2"></i>
            <h3 className="text-sm font-medium text-gray-900 mb-1">添加新指南</h3>
            <p className="text-xs text-gray-500 text-center mb-4">创建新的标注指南或上传文档</p>
            <button className="text-blue-600 hover:text-blue-700 text-sm cursor-pointer">
              创建指南
            </button>
          </div>
        </div>
      )}

      {/* Create Project Modal */}
      {showCreateProjectModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-[500px] max-w-90vw">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">创建新项目</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  项目名称 *
                </label>
                <input
                  type="text"
                  value={newProjectForm.name}
                  onChange={(e) => setNewProjectForm({...newProjectForm, name: e.target.value})}
                  placeholder="输入项目名称"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  项目描述
                </label>
                <textarea
                  value={newProjectForm.description}
                  onChange={(e) => setNewProjectForm({...newProjectForm, description: e.target.value})}
                  placeholder="输入项目描述..."
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  项目类型
                </label>
                <select 
                  value={newProjectForm.type}
                  onChange={(e) => setNewProjectForm({...newProjectForm, type: e.target.value})}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="">选择项目类型</option>
                  <option value="financial">财务分析</option>
                  <option value="legal">法律文档</option>
                  <option value="technical">技术文档</option>
                  <option value="product">产品文档</option>
                  <option value="other">其他</option>
                </select>
              </div>

              {/* AI草稿自动生成配置 */}
              <div className="border border-blue-200 rounded-lg p-4 bg-blue-50">
                <div className="flex items-start space-x-3">
                  <i className="ri-magic-line w-5 h-5 flex items-center justify-center text-blue-600 mt-0.5"></i>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-sm font-medium text-blue-900">
                        Auto-Generate Draft on Assign
                      </label>
                      <label className="relative inline-flex items-center cursor-pointer">
                        <input
                          type="checkbox"
                          checked={newProjectForm.autoGenerateDraft}
                          onChange={(e) => setNewProjectForm({...newProjectForm, autoGenerateDraft: e.target.checked})}
                          className="sr-only peer"
                        />
                        <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                      </label>
                    </div>
                    <div className="text-xs text-blue-700">
                      {newProjectForm.autoGenerateDraft ? (
                        <>
                          <div className="font-medium mb-1">✓ 已启用自动生成</div>
                          <div>当任务分配给标注员时，系统将自动生成AI草稿，提高标注效率</div>
                        </>
                      ) : (
                        <>
                          <div className="font-medium mb-1">✗ 手动生成模式</div>
                          <div>标注员需要在工作台手动点击"Generate Draft"来生成AI草稿</div>
                        </>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="flex items-center justify-end space-x-3 mt-6">
              <button
                onClick={() => {
                  setShowCreateProjectModal(false);
                  setNewProjectForm({
                    name: '',
                    description: '',
                    type: '',
                    autoGenerateDraft: true
                  });
                }}
                className="px-4 py-2 text-sm text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg whitespace-nowrap cursor-pointer"
              >
                取消
              </button>
              <button
                onClick={async () => {
                  try {
                    const newProject = await API.projects.create({
                      org_id: 1,
                      name: newProjectForm.name,
                      description: newProjectForm.description,
                      client_pm_id: 1,
                    });

                    // Add new project to the list
                    const transformedProject = {
                      id: newProject.project_id,
                      name: newProject.name,
                      description: newProject.description || '',
                      fileCount: 0,
                      totalPages: 0,
                      totalTables: 0,
                      status: newProject.status,
                      createdAt: new Date(newProject.created_at).toLocaleDateString(),
                      autoGenerateDraft: newProjectForm.autoGenerateDraft,
                      files: []
                    };

                    setProjects([transformedProject, ...projects]);
                    setShowCreateProjectModal(false);
                    setNewProjectForm({
                      name: '',
                      description: '',
                      type: '',
                      autoGenerateDraft: true
                    });

                    alert('✅ 项目创建成功！');
                  } catch (error) {
                    console.error('Failed to create project:', error);
                    alert('❌ 创建项目失败，请检查后端连接');
                  }
                }}
                disabled={!newProjectForm.name.trim()}
                className="px-4 py-2 text-sm text-white bg-blue-600 hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed rounded-lg whitespace-nowrap cursor-pointer"
              >
                创建项目
              </button>
            </div>
          </div>
        </div>
      )}

      {/* File Detail Modal - 显示解析的表格列表 */}
      {selectedFile && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          onClick={(e) => {
            if (e.target === e.currentTarget) {
              setSelectedFile(null);
            }
          }}
        >
          <div className="bg-white rounded-lg p-6 w-[90vw] max-w-[1000px] max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">表格解析结果</h3>
              <button
                onClick={() => setSelectedFile(null)}
                className="text-gray-400 hover:text-gray-600 cursor-pointer p-1 rounded-full hover:bg-gray-100"
                title="关闭"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            
            <div className="space-y-4 mb-6">
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <label className="block font-medium text-gray-700 mb-1">文件名</label>
                  <p className="text-gray-900">{selectedFile.name}</p>
                </div>
                <div>
                  <label className="block font-medium text-gray-700 mb-1">总页数</label>
                  <p className="text-gray-900">{selectedFile.pages}</p>
                </div>
                <div>
                  <label className="block font-medium text-gray-700 mb-1">表格数量</label>
                  <p className="text-gray-900">{selectedFile.tables}</p>
                </div>
              </div>
            </div>

            {selectedFile.parsedTables && selectedFile.parsedTables.length > 0 && (
              <div>
                <h4 className="text-md font-semibold text-gray-900 mb-3">解析的表格列表</h4>
                <div className="space-y-6">
                  {selectedFile.parsedTables.map((table: any, index: number) => (
                    <div key={table.id} className="border border-gray-200 rounded-lg p-4">
                      <div className="flex items-center justify-between mb-3">
                        <h5 className="text-sm font-semibold text-gray-900">
                          表格 #{table.id} (第 {table.page} 页)
                        </h5>
                        <div className="flex items-center space-x-2">
                          <span className="text-xs text-gray-500">
                            {table.rows}×{table.cols} | 置信度: {Math.round((table.confidence || 0) * 100)}%
                          </span>
                          <span className={`px-2 py-1 text-xs rounded-full ${getComplexityColor(table.complexity)}`}>
                            {getComplexityLabel(table.complexity)}
                          </span>
                        </div>
                      </div>
                      
                      {/* 显示实际表格内容 */}
                      {table.headers && table.tableRows && (
                        <div className="overflow-x-auto border border-gray-200 rounded">
                          <table className="min-w-full border-collapse">
                            <thead className="bg-gray-50">
                              <tr>
                                {table.headers[0]?.map((header: string, colIndex: number) => (
                                  <th
                                    key={colIndex}
                                    className="border border-gray-200 px-3 py-2 text-left text-xs font-medium text-gray-700 uppercase tracking-wider"
                                  >
                                    {header || `列 ${colIndex + 1}`}
                                  </th>
                                ))}
                              </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-gray-200">
                              {table.tableRows.slice(0, 10).map((row: string[], rowIndex: number) => (
                                <tr key={rowIndex} className={rowIndex % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                                  {row.map((cell: string, cellIndex: number) => (
                                    <td
                                      key={cellIndex}
                                      className="border border-gray-200 px-3 py-2 text-sm text-gray-900"
                                    >
                                      {cell || '-'}
                                    </td>
                                  ))}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                          {table.tableRows.length > 10 && (
                            <div className="text-xs text-gray-500 px-3 py-2 bg-gray-50 border-t border-gray-200">
                              显示前 10 行，共 {table.tableRows.length} 行
                            </div>
                          )}
                        </div>
                      )}
                      
                      {/* 表格元数据 */}
                      <div className="mt-3 text-xs text-gray-500">
                        <span className="font-mono">位置: [{table.bbox.join(', ')}]</span>
                        <span className="mx-2">|</span>
                        <span>状态: {getStatusLabel(table.status)}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
            
            <div className="flex items-center justify-between mt-6 pt-4 border-t border-gray-200">
              <div className="text-sm text-gray-500">
                共 {selectedFile.parsedTables?.length || 0} 个表格
              </div>
              <div className="flex items-center space-x-3">
                <button
                  onClick={() => setSelectedFile(null)}
                  className="px-6 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg whitespace-nowrap cursor-pointer transition-colors"
                >
                  关闭
                </button>
                <button className="px-6 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg whitespace-nowrap cursor-pointer transition-colors">
                  查看PDF
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Upload Modal */}
      {showUploadModal && selectedProject && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-[500px] max-w-90vw">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">上传PDF文件</h3>
            <p className="text-sm text-gray-600 mb-4">项目：{selectedProject.name}</p>
            
            <div className="space-y-4">
              {!isUploading && !isParsing && !showParseResults && (
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
                  <i className="ri-upload-cloud-line w-12 h-12 flex items-center justify-center text-gray-400 mx-auto mb-4"></i>
                  <p className="text-sm text-gray-600 mb-2">拖拽文件到此处或点击选择</p>
                  <p className="text-xs text-gray-500 mb-4">支持 PDF 格式，最大 50MB</p>
                  <p className="text-xs text-blue-600 mb-4">上传后将自动解析表格结构并创建任务</p>
                  <input 
                    type="file" 
                    accept=".pdf" 
                    className="hidden" 
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleFileUpload(file);
                    }}
                    id="file-upload"
                  />
                  <label 
                    htmlFor="file-upload"
                    className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 text-sm whitespace-nowrap cursor-pointer inline-block"
                  >
                    选择文件
                  </label>
                </div>
              )}

              {/* Upload Progress */}
              {isUploading && (
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <i className="ri-upload-line w-5 h-5 flex items-center justify-center text-blue-600"></i>
                    <span className="text-sm font-medium text-gray-900">正在上传文件...</span>
                    <span className="text-sm text-gray-600">{uploadProgress}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-blue-600 h-2 rounded-full transition-all duration-300"
                      style={{ width: `${uploadProgress}%` }}
                    ></div>
                  </div>
                </div>
              )}

              {/* Parse Progress */}
              {isParsing && (
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <i className="ri-search-line w-5 h-5 flex items-center justify-center text-green-600 animate-spin"></i>
                    <span className="text-sm font-medium text-gray-900">正在解析表格结构...</span>
                    <span className="text-sm text-gray-600">{parseProgress}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-green-600 h-2 rounded-full transition-all duration-300"
                      style={{ width: `${parseProgress}%` }}
                    ></div>
                  </div>
                  <p className="text-xs text-gray-500">正在识别表格位置、行列结构、合并单元格等信息...</p>
                </div>
              )}
            </div>
            
            <div className="flex items-center justify-end space-x-3 mt-6">
              <button
                onClick={() => {
                  if (isParsing) {
                    // Cancel the parsing process
                    setCancelParsing(true);
                    setIsParsing(false);
                    setParseProgress(0);
                    setCurrentParsingFileId(null);
                  }
                  setShowUploadModal(false);
                  setIsUploading(false);
                  setUploadProgress(0);
                }}
                disabled={isUploading}
                className="px-4 py-2 text-sm text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg whitespace-nowrap cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isParsing ? '取消解析' : '取消'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Parse Results Modal */}
      {showParseResults && parseResults && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-[700px] max-w-90vw max-h-80vh overflow-y-auto">
            <div className="flex items-center space-x-3 mb-4">
              <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center">
                <i className="ri-check-line w-4 h-4 flex items-center justify-center text-green-600"></i>
              </div>
              <h3 className="text-lg font-semibold text-gray-900">解析完成</h3>
            </div>
            
            <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-6">
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <div className="font-medium text-green-900">文件名</div>
                  <div className="text-green-700">{parseResults.fileName}</div>
                </div>
                <div>
                  <div className="font-medium text-green-900">总页数</div>
                  <div className="text-green-700">{parseResults.totalPages} 页</div>
                </div>
                <div>
                  <div className="font-medium text-green-900">发现表格</div>
                  <div className="text-green-700">{parseResults.tablesFound} 个</div>
                </div>
              </div>
            </div>

            <div className="mb-6">
              <h4 className="text-md font-semibold text-gray-900 mb-3">表格详情</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-gray-50 border-b border-gray-200">
                    <tr>
                      <th className="text-left py-2 px-3 font-medium text-gray-900">表格</th>
                      <th className="text-left py-2 px-3 font-medium text-gray-900">页码</th>
                      <th className="text-left py-2 px-3 font-medium text-gray-900">行/列</th>
                      <th className="text-left py-2 px-3 font-medium text-gray-900">复杂度</th>
                      <th className="text-left py-2 px-3 font-medium text-gray-900">脚注</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    {parseResults.tables.map((table: any) => (
                      <tr key={table.id} className="hover:bg-gray-50">
                        <td className="py-2 px-3">
                          <span className="font-mono text-blue-600">表格 #{table.id}</span>
                        </td>
                        <td className="py-2 px-3">
                          <span className="text-gray-900">第 {table.page} 页</span>
                        </td>
                        <td className="py-2 px-3">
                          <span className="text-gray-900">{table.rows}×{table.cols}</span>
                        </td>
                        <td className="py-2 px-3">
                          <span className={`px-2 py-1 text-xs rounded-full ${getComplexityColor(table.complexity)}`}>
                            {getComplexityLabel(table.complexity)}
                          </span>
                        </td>
                        <td className="py-2 px-3">
                          <span className={`px-2 py-1 text-xs rounded-full ${table.hasFootnotes ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800'}`}>
                            {table.hasFootnotes ? '有' : '无'}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
              <div className="flex items-start space-x-3">
                <i className="ri-information-line w-5 h-5 flex items-center justify-center text-blue-600 mt-0.5"></i>
                <div className="text-sm">
                  <div className="font-medium text-blue-900 mb-1">任务创建说明</div>
                  <div className="text-blue-700">
                    • 每个表格将创建为独立的标注任务<br/>
                    • 所有任务将进入"待分配"状态<br/>
                    • 系统管理员可在"任务分配管理"中分配任务<br/>
                    • 当前项目的AI草稿设置：{selectedProject?.autoGenerateDraft ? '自动生成已启用' : '需手动生成'}
                  </div>
                </div>
              </div>
            </div>
            
            <div className="flex items-center justify-end space-x-3">
              <button
                onClick={() => {
                  setShowParseResults(false);
                  setParseResults(null);
                  setShowUploadModal(false);
                }}
                className="px-4 py-2 text-sm text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg whitespace-nowrap cursor-pointer"
              >
                取消
              </button>
              <button
                onClick={handleConfirmParsing}
                className="px-4 py-2 text-sm text-white bg-blue-600 hover:bg-blue-700 rounded-lg whitespace-nowrap cursor-pointer"
              >
                确认并创建任务
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
